# Generated by Django 4.1.1 on 2022-10-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('street', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('zip', models.IntegerField()),
                ('website', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=250)),
                ('opening_hours', models.CharField(max_length=250)),
                ('price_level', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
            ],
        ),
    ]
